### PR TITLE
Fixed markdown, formatting and typographic issues.

### PR DESCRIPTION
**Pull request by honmanyau**
Changes made according to Issue #2. The only markdown issue were links getting parsed as code instead because they were wrapped with back ticks at the wrong places. Additional minor formatting and typographic changes were also made.

### CODE REVIEW

**Comment by NoobTW** [comment]
Fantastic, I think we can close #2. Keep going for the Hacktoberfest ;)

**Comment by honmanyau** [comment]
Awesome! :) I'm not sure if there are other formatting issues in other articles and am actually in the process of going through them; would it be worthwhile keeping the issue open for now so that it can be used for documentation in case related issues come up (unless you've already been through them, of course!)?

**Comment by honmanyau** [comment]
Oh! Looks like I was a couple of minutes too late—please disregard the previous message then! I will open an issue if I spot anything! Have a nice day!

**Comment by NoobTW** [comment]
It seems there's no more Markdown formatting issues. But feel free to re-open that if you find any.

**Pull request merged**
